### ISSUE TITLE
critical path on DEG

### ISSUE THREAD

**Issue by songmuhan** [baichen318/arch-explorer#2]
Hi,

 I'm curious about why you chose to focus on a single critical path rather than exploring all possible critical paths. Was this a deliberate decision? 

Thank you for your insightful work :)

**Comment by baichen318** [comment]
Hi @songmuhan ,

Thanks for your question.

We focus on **the single but representative** critical path.

The critical path uncovers whether and how a parameter affects the microexecution due to resource constraints. Many critical paths can be constructed, but the true root cause, i.e., the primary bottleneck, should be captured and optimized preferentially.

We optimize the primary bottleneck in each DSE loop, hoping to receive incremental benefits gradually in multiple iterations.

Best regards,
Chen

**Comment by songmuhan** [comment]
Hi @baichen318,

Thank you for the clarification. Your approach makes perfect sense.
